const {randomUUID}=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const bcrypt=require('bcryptjs');
const express=require('express');
const {chromium,expect:baseExpect}=require('@playwright/test');
const expect=baseExpect.configure({timeout:30000});
const { createTestApp } = require('./support/database');
async function listen(app){const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));return server;}
async function run(){
  const email=`browser-${randomUUID()}@example.com`,password=randomUUID();
  const staticApp=express();staticApp.use(express.static('P:/BevShopFe/build'));
  staticApp.get('*',(req,res)=>res.sendFile('P:/BevShopFe/build/index.html'));
  const frontend=await listen(staticApp);
  process.env.FRONTEND_URL=`http://127.0.0.1:${frontend.address().port}`;
  const { app, database } = await createTestApp();
  await database.query('INSERT INTO users(id,email,username,password,first_name,last_name,role) VALUES($1,$2,$2,$3,$4,$5,$6)',[randomUUID(),email,await bcrypt.hash(password,12),'Browser','Test','ADMIN']);
  await database.query("UPDATE settings SET currency='RWF',timezone='Africa/Kigali',owner_id=(SELECT id FROM users LIMIT 1) WHERE id=1");
  const api=await listen(app);
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('http://localhost:4000/api/**',async route=>{
    const target=route.request().url().replace('http://localhost:4000',`http://127.0.0.1:${api.address().port}`);
    const response=await route.fetch({url:target});await route.fulfill({response});
  });
  try {
    await page.goto(`http://127.0.0.1:${frontend.address().port}/login`);
    await page.locator('input[name=email]').fill(email);
    await page.locator('input[name=password]').fill(password);
    await page.getByRole('button',{name:/^sign in$/i}).click();
    await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible({timeout:30000});
    await page.getByRole('link',{name:'Categories',exact:true}).click();
    await page.getByRole('button',{name:'Add Category',exact:true}).click();
    await page.getByLabel('Category name',{exact:true}).fill('Beverages');
    await page.getByRole('button',{name:'Save category',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Beverages',exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Products',exact:true}).click();
    const productName='Browser Fanta '+Date.now();
    await page.getByRole('button',{name:'Add Product',exact:true}).click();
    await page.getByLabel('Product name',{exact:true}).fill(productName);
    await page.locator('select[name=categoryId]').selectOption({label:'Beverages'});
    await page.getByLabel('Number of Packs',{exact:true}).fill('2');
    await page.getByLabel('Amount per Pack (RWF)',{exact:true}).fill('25000');
    await page.getByLabel('Selling price per item (RWF)',{exact:true}).fill('2500');
    await page.getByRole('button',{name:'Save product',exact:true}).click();
    await expect(page.getByRole('cell',{name:productName,exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Add Product',exact:true}).click();
    await page.getByLabel('Product name',{exact:true}).fill(productName);
    await page.locator('select[name=categoryId]').selectOption({label:'Beverages'});
    await page.getByLabel('Amount per Pack (RWF)',{exact:true}).fill('25000');
    await page.getByLabel('Selling price per item (RWF)',{exact:true}).fill('2500');
    await page.getByRole('button',{name:'Save product',exact:true}).click();
    await expect(page.getByText('This product already exists.',{exact:true})).toBeVisible();
    await expect(page.getByRole('button',{name:'Increase Stock',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Cancel',exact:true}).click();
    await page.getByRole('button',{name:'Add Product',exact:true}).click();
    await page.getByLabel('Product name',{exact:true}).fill('Coca-Cola');
    await page.locator('select[name=categoryId]').selectOption({label:'Beverages'});
    await page.getByLabel('Number of Packs',{exact:true}).fill('10');
    await page.getByLabel('Items per Pack',{exact:true}).fill('24');
    await page.getByLabel('Amount per Pack (RWF)',{exact:true}).fill('12000');
    await page.getByLabel('Selling price per item (RWF)',{exact:true}).fill('700');
    await page.getByRole('button',{name:'Save product',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Coca-Cola',exact:true})).toBeVisible();
    await expect(page.getByRole('row').filter({hasText:productName})).toContainText('Normal');
    await page.getByRole('link',{name:'Purchases',exact:true}).click();
    await page.getByRole('button',{name:'Add supplier',exact:true}).click();
    await page.getByLabel('Supplier name',{exact:true}).fill('Wholesaler');
    await page.getByRole('button',{name:'Save supplier',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Wholesaler',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Receive purchase',exact:true}).click();
    await page.locator('select[name=productId]').selectOption({label:productName});
    await page.locator('select[name=supplierId]').selectOption({label:'Wholesaler'});
    await page.getByLabel('Number of packs',{exact:true}).fill('1');await page.getByLabel('Purchase price per pack (RWF)',{exact:true}).fill('25000');
    await page.getByRole('button',{name:'Save purchase',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('status').filter({hasText:'Saved successfully.'})).toHaveText('Saved successfully.');
    await page.getByRole('link',{name:'Sales',exact:true}).click();
    await page.locator('select[name=productId]').selectOption({label:`${productName} — 36 individual items`});
    await page.getByLabel('Individual items sold',{exact:true}).fill('3');
    await page.getByRole('button',{name:'+ Add another item',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Total: RWF 7,500',exact:true})).toBeVisible();
    await page.locator('select[name=productId]').selectOption({label:'Coca-Cola — 240 individual items'});
    await page.getByLabel('Individual items sold',{exact:true}).fill('5');
    await page.getByRole('button',{name:'+ Add another item',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Total: RWF 11,000',exact:true})).toBeVisible();
    await page.locator('select[name=paymentMethod]').selectOption('mobile_money');
    await page.getByRole('button',{name:'Record paid sale',exact:true}).click();
    await expect(page.getByRole('heading',{name:'SALE RECEIPT',exact:true})).toBeVisible();
    await expect(page.getByRole('dialog')).toContainText('Grand total: RWF 11,000');
    await expect(page.getByRole('dialog').getByRole('cell',{name:'Coca-Cola',exact:true})).toBeVisible();
    await page.screenshot({path:path.resolve('artifacts/shop-receipt.png'),fullPage:true});
    await page.getByRole('button',{name:'Close',exact:true}).click();
    await page.getByRole('link',{name:'Expenses',exact:true}).click();
    await page.getByRole('button',{name:'Record Expense',exact:true}).click();
    await page.locator('input[name=category]').fill('Security');await page.getByLabel('Amount paid (RWF)',{exact:true}).fill('1000');
    await page.getByRole('button',{name:'Save expense',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('status').filter({hasText:'Saved successfully.'})).toHaveText('Saved successfully.');
    await page.getByRole('link',{name:'Damaged products',exact:true}).click();
    await page.locator('select[name=productId]').selectOption({label:`${productName} — 33 individual items`});
    await page.getByLabel('Individual items lost',{exact:true}).fill('1');
    await page.getByLabel('Reason',{exact:true}).fill('Broken bottle');
    await page.getByRole('button',{name:'Record stock loss',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Broken bottle',exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Products',exact:true}).click();
    await expect(page.getByRole('row').filter({hasText:productName})).toContainText('32');
    fs.mkdirSync('artifacts',{recursive:true});
    await page.screenshot({path:path.resolve('artifacts/shop-products.png'),fullPage:true});
    await page.getByRole('link',{name:'Owner money',exact:true}).click();
    await page.getByRole('button',{name:'Record owner money',exact:true}).click();
    await page.getByLabel('Amount (RWF)',{exact:true}).fill('50000');
    await page.getByLabel('Details / reason',{exact:true}).fill('Owner deposit');
    await page.getByRole('button',{name:'Save owner money',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Owner deposit',exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Activity',exact:true}).click();
    const downloadPromise=page.waitForEvent('download');
    await page.getByRole('button',{name:'Print / Export PDF',exact:true}).click();
    const download=await downloadPromise;await download.saveAs(path.resolve('artifacts/shop-activity.pdf'));
    if(!fs.readFileSync('artifacts/shop-activity.pdf').subarray(0,4).equals(Buffer.from('%PDF')))throw Error('Invalid PDF export');
    await page.getByRole('link',{name:'Reports',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Money movement',exact:true})).toBeVisible();
    await page.locator('select').first().selectOption('yearly');
    await expect(page.getByRole('heading',{name:'Money movement',exact:true})).toBeVisible();
    await page.screenshot({path:path.resolve('artifacts/shop-reports.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.resolve('artifacts/shop-mobile.png'),fullPage:true});
    if(errors.length)throw new Error(errors.join('\n'));
    console.log('Browser checks passed: login, category, initial stock, supplier purchase, sale receipt, expense, damaged stock, inventory, yearly report and mobile rendering.');
  } catch(error) {
    fs.mkdirSync('artifacts',{recursive:true});
    await page.screenshot({path:path.resolve('artifacts/shop-browser-failure.png'),fullPage:true});
    console.error('Browser state:',await page.locator('body').innerText());
    console.error('Page errors:',errors);
    throw error;
  } finally {
    await page.unrouteAll({behavior:'ignoreErrors'});
    await browser.close();await new Promise(resolve=>frontend.close(resolve));await new Promise(resolve=>api.close(resolve));await database.close();
  }
}
run().catch(e=>{console.error(e.message);process.exitCode=1;});
